name: Flutter Build (Manual)
run-name: "RustDesk Build #${{ github.run_number }} | ${{ github.event.inputs.upload-tag || 'dev' }} | @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "Release Tag (格式建议: MMDD-HHMMSS)"
        required: false
        default: ""

jobs:
  run-flutter-manual-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "${{ github.event.inputs.upload-tag || 'dev' }}"
